### ISSUE TITLE
似たようなプロジェクトを探す

### ISSUE THREAD

**Issue by Hattyoriiiiiii** [Hattyoriiiiiii/mobile-trash-can#1]

**Comment by Hattyoriiiiiii** [comment]
## [ゴミ箱がゴミを判別する「ゴミソムリエ」、機械学習を活用して分別の精度を高める](https://project.nikkeibp.co.jp/pc/atcl/20/08/04/00032/090200034/)
- カメラに捨てたいゴミをかざすと画像認識が実行され、ペットボトルと判別されればふたが開く仕組み
- ふたには人感センサーも取り付けてあり、人が近づいたときに画像認識が実行
- ふたの開閉はラズパイに接続したモーターで制御
- 電源はモバイルバッテリーで確保
- 画像認識は、ラズパイにUSBで接続した、米Google社のAIアクセラレーター「Coral Edge」で実行

**Comment by Hattyoriiiiiii** [comment]
## [ゴミ箱がゴミを判別する「ゴミソムリエ」、機械学習を活用して分別の精度を高める](https://project.nikkeibp.co.jp/pc/atcl/20/08/04/00032/090200034/)
- カメラに捨てたいゴミをかざすと画像認識が実行され、ペットボトルと判別されればふたが開く仕組み
- ふたには人感センサーも取り付けてあり、人が近づいたときに画像認識が実行
- ふたの開閉はラズパイに接続したモーターで制御
- 電源はモバイルバッテリーで確保
- 画像認識は、ラズパイにUSBで接続した、米Google社のAIアクセラレーター「Coral Edge」で実行

**Comment by 2000lilu0317** [comment]
### 勝手に入るゴミ箱

https://gigazine.net/news/20130212-smart-trashbox-jmaf-16th/

・ゴミを投げたら、ゴミ箱がゴミの落下点を予測してやってくる
・ゲームっぽい

**Comment by 2000lilu0317** [comment]
### 未来のゴミ箱

https://robotstart.info/2019/10/20/jjpc-4thprog-competition.html
